### ISSUE TITLE
numpy version doesn't work

### ISSUE THREAD

**Issue by RomanKoshkin** [eridgd/WCT-TF#12]
If I uncomment the predict_np() function, it gives me an error during runtime saying that it cannot find "style_encoded" in the model object. Apparently, the  it is not formed in the WCTModel() class in the recent versions. Please help. I am quite new to Python. Thanks.

**Comment by eridgd** [comment]
This is now fully implemented, please see this branch https://github.com/eridgd/WCT-TF/tree/numpy-wct

To use, add the `--np-wct` flag for webcam.py or stylize.py.

**Comment by RomanKoshkin** [comment]
I am sorry @eridgd, to bother you again with what may seem such a petty question. I have cloned this branch into my local repo, ran the stylize.py with the `--np-wct` parameter on, but the code doesn't use the `wct_np` function in the `ops.py` module at all. I checked it in the debug mode. However, it does use the `wct_tf` function in that same module. Sorry for this (I am really new to Python and TF), but it couldn't figure out this happens. Please help.

**Comment by eridgd** [comment]
Hi,

I gave this a try with stylize.py and it does seem to be using the right WCT block with --np-wct. If you add a regular print statement somewhere in wct_np it should display on executing (printing with TF requires adding a tf.Print op https://stackoverflow.com/a/42443594). Another indication that it is using the NP WCT is that it will take 3x as long to finish.

If you're still finding it using the wrong op, can you please share the options you're running the script with?

**Comment by RomanKoshkin** [comment]
Everything works fine. I tried to stop the execution of the whole code by adding a breakpoint in the `wct_np` function, but the code did not stop for some reason. However, adding a breakpoint in the `wct_tf` function does stop the execution. That behavior is strange to me. Perhaps `wct_np` becomes part of the TF session that cannot be stopped in the middle of execution. I followed your advice to add a `print` statement into the `wct_np` and it does print whatever I ask it to print. I just wanted to inspect the variables. What I did was to use multiple statements like this:
 `print("style_t")`
  `print("type of variable {}, size of variable {}".format(type(style_t), style_t.shape))`
I know it looks superugly. If stopping the code doesn't work, looks like I'll have to try pickling the tensors for inspection later (not sure if this will work for me). Thank you.

**Comment by eridgd** [comment]
Try adding this to `wct_np`:

`import IPython; IPython.embed()`

That should drop you to a shell in the middle of execution and allow for manipulation/printing of tensors (though you may have to run it outside the debugger).

`wct_tf` acts in a subtly different way due to TF. That function is called before the session starts to add ops to the graph, so adding a breakpoint will only interrupt the graph building phase. If you want to print tensors you'll need to add a `tf.Print` op to the graph, or use tfdbg - https://www.tensorflow.org/programmers_guide/debugger
