### ISSUE TITLE
Processing time

### ISSUE THREAD

**Issue by Sugarbank** [eridgd/WCT-TF#15]
Hi,
There's a stream of stuff before the processing begins...
just wondering if it's possible to not print out this stuff or reduce it as it takes quite alot of time before the image processing begins?Sorry if this is a dumb question.

Using TensorFlow backend.
Loading VGG up to layer relu5_1
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
vgg_input (InputLayer)       (None, None, None, 3)     0         
_________________________________________________________________
preprocess (Conv2D)          (None, None, None, 3)     12        
_________________________________________________________________
lambda_1 (Lambda)            (None, None, None, 3)     0         
_________________________________________________________________
conv1_1 (Conv2D)             (None, None, None, 64)    1792      
_________________________________________________________________
relu1_1 (Activation)         (None, None, None, 64)    0         
_________________________________________________________________
lambda_2 (Lambda)            (None, None, None, 64)    0         
_________________________________________________________________
conv1_2 (Conv2D)             (None, None, None, 64)    36928     
_________________________________________________________________
relu1_2 (Activation)         (None, None, None, 64)    0         
_________________________________________________________________
pool1 (MaxPooling2D)         (None, None, None, 64)    0         
_________________________________________________________________
lambda_3 (Lambda)            (None, None, None, 64)    0         
_________________________________________________________________
conv2_1 (Conv2D)             (None, None, None, 128)   73856     
_________________________________________________________________
relu2_1 (Activation)         (None, None, None, 128)   0         
_________________________________________________________________
lambda_4 (Lambda)            (None, None, None, 128)   0         
_________________________________________________________________
conv2_2 (Conv2D)             (None, None, None, 128)   147584    
_________________________________________________________________
relu2_2 (Activation)         (None, None, None, 128)   0         
_________________________________________________________________
pool2 (MaxPooling2D)         (None, None, None, 128)   0         
_________________________________________________________________
lambda_5 (Lambda)            (None, None, None, 128)   0         
_________________________________________________________________
conv3_1 (Conv2D)             (None, None, None, 256)   295168    
_________________________________________________________________
relu3_1 (Activation)         (None, None, None, 256)   0         
_________________________________________________________________
lambda_6 (Lambda)            (None, None, None, 256)   0         
_________________________________________________________________
conv3_2 (Conv2D)             (None, None, None, 256)   590080    
_________________________________________________________________
relu3_2 (Activation)         (None, None, None, 256)   0         
_________________________________________________________________
lambda_7 (Lambda)            (None, None, None, 256)   0         
_________________________________________________________________
conv3_3 (Conv2D)             (None, None, None, 256)   590080    
_________________________________________________________________
relu3_3 (Activation)         (None, None, None, 256)   0         
_________________________________________________________________
lambda_8 (Lambda)            (None, None, None, 256)   0         
_________________________________________________________________
conv3_4 (Conv2D)             (None, None, None, 256)   590080    
_________________________________________________________________
relu3_4 (Activation)         (None, None, None, 256)   0         
_________________________________________________________________
pool3 (MaxPooling2D)         (None, None, None, 256)   0         
_________________________________________________________________
lambda_9 (Lambda)            (None, None, None, 256)   0         
_________________________________________________________________
conv4_1 (Conv2D)             (None, None, None, 512)   1180160   
_________________________________________________________________
relu4_1 (Activation)         (None, None, None, 512)   0         
_________________________________________________________________
lambda_10 (Lambda)           (None, None, None, 512)   0         
_________________________________________________________________
conv4_2 (Conv2D)             (None, None, None, 512)   2359808   
_________________________________________________________________
relu4_2 (Activation)         (None, None, None, 512)   0         
_________________________________________________________________
lambda_11 (Lambda)           (None, None, None, 512)   0         
_________________________________________________________________
conv4_3 (Conv2D)             (None, None, None, 512)   2359808   
_________________________________________________________________
relu4_3 (Activation)         (None, None, None, 512)   0         
_________________________________________________________________
lambda_12 (Lambda)           (None, None, None, 512)   0         
_________________________________________________________________
conv4_4 (Conv2D)             (None, None, None, 512)   2359808   
_________________________________________________________________
relu4_4 (Activation)         (None, None, None, 512)   0         
_________________________________________________________________
pool4 (MaxPooling2D)         (None, None, None, 512)   0         
_________________________________________________________________
lambda_13 (Lambda)           (None, None, None, 512)   0         
_________________________________________________________________
conv5_1 (Conv2D)             (None, None, None, 512)   2359808   
_________________________________________________________________
relu5_1 (Activation)         (None, None, None, 512)   0         
=================================================================
Total params: 12,944,972
Trainable params: 0
Non-trainable params: 12,944,972
_________________________________________________________________
None
Building encoder/decoder for relu target relu5_1
WARNING:tensorflow:From /Volumes/SUGARBANK_SSD/SUGARBANK/STYLA_RENDER_TEST/software/WCT-TF-master/ops.py:160: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /Volumes/SUGARBANK_SSD/SUGARBANK/STYLA_RENDER_TEST/software/WCT-TF-master/ops.py:234: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
WARNING:tensorflow:From /Volumes/SUGARBANK_SSD/SUGARBANK/STYLA_RENDER_TEST/software/WCT-TF-master/ops.py:262: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
decoder_input_relu5_1 (Input (None, None, None, 512)   0         
_________________________________________________________________
relu5_1_0 (Lambda)           (None, None, None, 512)   0         
_________________________________________________________________
relu5_1_1 (UpSampling2D)     (None, None, None, 512)   0         
_________________________________________________________________
relu5_1_2 (Lambda)           (None, None, None, 512)   0         
_________________________________________________________________
relu5_1_3 (Lambda)           (None, None, None, 512)   0         
_________________________________________________________________
relu5_1_4 (Lambda)           (None, None, None, 512)   0         
_________________________________________________________________
relu5_1_5 (Lambda)           (None, None, None, 256)   0         
_________________________________________________________________
relu5_1_6 (UpSampling2D)     (None, None, None, 256)   0         
_________________________________________________________________
relu5_1_7 (Lambda)           (None, None, None, 256)   0         
_________________________________________________________________
relu5_1_8 (Lambda)           (None, None, None, 256)   0         
_________________________________________________________________
relu5_1_9 (Lambda)           (None, None, None, 256)   0         
_________________________________________________________________
relu5_1_10 (Lambda)          (None, None, None, 128)   0         
_________________________________________________________________
relu5_1_11 (UpSampling2D)    (None, None, None, 128)   0         
_________________________________________________________________
relu5_1_12 (Lambda)          (None, None, None, 128)   0         
_________________________________________________________________
relu5_1_13 (Lambda)          (None, None, None, 64)    0         
_________________________________________________________________
relu5_1_14 (UpSampling2D)    (None, None, None, 64)    0         
_________________________________________________________________
relu5_1_15 (Lambda)          (None, None, None, 64)    0         
_________________________________________________________________
relu5_1_16 (Lambda)          (None, None, None, 3)     0         
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
None
Building encoder/decoder for relu target relu4_1
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
decoder_input_relu4_1 (Input (None, None, None, 512)   0         
_________________________________________________________________
relu4_1_0 (Lambda)           (None, None, None, 256)   0         
_________________________________________________________________
relu4_1_1 (UpSampling2D)     (None, None, None, 256)   0         
_________________________________________________________________
relu4_1_2 (Lambda)           (None, None, None, 256)   0         
_________________________________________________________________
relu4_1_3 (Lambda)           (None, None, None, 256)   0         
_________________________________________________________________
relu4_1_4 (Lambda)           (None, None, None, 256)   0         
_________________________________________________________________
relu4_1_5 (Lambda)           (None, None, None, 128)   0         
_________________________________________________________________
relu4_1_6 (UpSampling2D)     (None, None, None, 128)   0         
_________________________________________________________________
relu4_1_7 (Lambda)           (None, None, None, 128)   0         
_________________________________________________________________
relu4_1_8 (Lambda)           (None, None, None, 64)    0         
_________________________________________________________________
relu4_1_9 (UpSampling2D)     (None, None, None, 64)    0         
_________________________________________________________________
relu4_1_10 (Lambda)          (None, None, None, 64)    0         
_________________________________________________________________
relu4_1_11 (Lambda)          (None, None, None, 3)     0         
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
None
Building encoder/decoder for relu target relu3_1
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
decoder_input_relu3_1 (Input (None, None, None, 256)   0         
_________________________________________________________________
relu3_1_0 (Lambda)           (None, None, None, 128)   0         
_________________________________________________________________
relu3_1_1 (UpSampling2D)     (None, None, None, 128)   0         
_________________________________________________________________
relu3_1_2 (Lambda)           (None, None, None, 128)   0         
_________________________________________________________________
relu3_1_3 (Lambda)           (None, None, None, 64)    0         
_________________________________________________________________
relu3_1_4 (UpSampling2D)     (None, None, None, 64)    0         
_________________________________________________________________
relu3_1_5 (Lambda)           (None, None, None, 64)    0         
_________________________________________________________________
relu3_1_6 (Lambda)           (None, None, None, 3)     0         
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
None
Building encoder/decoder for relu target relu2_1
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
decoder_input_relu2_1 (Input (None, None, None, 128)   0         
_________________________________________________________________
relu2_1_0 (Lambda)           (None, None, None, 64)    0         
_________________________________________________________________
relu2_1_1 (UpSampling2D)     (None, None, None, 64)    0         
_________________________________________________________________
relu2_1_2 (Lambda)           (None, None, None, 64)    0         
_________________________________________________________________
relu2_1_3 (Lambda)           (None, None, None, 3)     0         
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
None
Building encoder/decoder for relu target relu1_1
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
decoder_input_relu1_1 (Input (None, None, None, 64)    0         
_________________________________________________________________
relu1_1_0 (Lambda)           (None, None, None, 64)    0         
_________________________________________________________________
relu1_1_1 (Lambda)           (None, None, None, 3)     0         
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
None
2018-02-26 19:07:11.345208: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
Restoring vars for relu5_1 from checkpoint models/relu5_1/model.ckpt-15004
Restoring vars for relu4_1 from checkpoint models/relu4_1/model.ckpt-15003
Restoring vars for relu3_1 from checkpoint models/relu3_1/model.ckpt-15003
Restoring vars for relu2_1 from checkpoint models/relu2_1/model.ckpt-15000
Restoring vars for relu1_1 from checkpoint models/relu1_1/model.ckpt-15002

**Comment by eridgd** [comment]
Printing the model summary doesn't affect the overall setup time, but if you want to suppress the output comment out these two lines:

https://github.com/eridgd/WCT-TF/blob/54a686010bf4ecaad775649a76044cdfff445ecf/model.py#L63
https://github.com/eridgd/WCT-TF/blob/54a686010bf4ecaad775649a76044cdfff445ecf/model.py#L302

**Comment by Sugarbank** [comment]
Cheers for the response.That makes sense. Just wondering how I could process new images with the script without it building all the layers etc. 
eg. how does the webcam script work so it doesnt have to do all the preloading everyframe?
Thanks in advance:)

**Comment by eridgd** [comment]
Thanks for clarifying,

The preloading of the model is only performed once during initial setup of the webcam script, at https://github.com/eridgd/WCT-TF/blob/38fedaa49e1da6885896748c827d227887045017/webcam.py#L140

That calls https://github.com/eridgd/WCT-TF/blob/38fedaa49e1da6885896748c827d227887045017/wct.py#L31-L58 to build the graph and load the trained weights from a checkpoint. That only has to be done once upfront, and then subsequent webcam images forwarded through the model use the cached architecture without having to reload every frame.

**Comment by Sugarbank** [comment]
thanks so much for the info.That's really helpfull:) cheers
