### ISSUE TITLE
Cannot stylize video.

### ISSUE THREAD

**Issue by kobykotiv** [eridgd/WCT-TF#19]
The FFMPEG can strip the video of its frames, but when it needs to stylize the images it breaks. I'm using Windows 10.

I get `AttributeError: 'str' object has no attribute 'shape'` When I try to stylize video. 
Please help?

**Comment by eridgd** [comment]
I don't have access to a Windows machine to test this, unfortunately. Are you able to stylize single images using stylize.py?

**Comment by kobykotiv** [comment]
Yes I am.
and it works wonderfully with my gtx 1050ti.
But Video doesn't work.

**Comment by kobykotiv** [comment]
The more detailed error i get is 

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
T:\__ML\TF_universal_Style_Transfer\stylize_video.py in <module>()
    121
    122 if __name__ == '__main__':
--> 123     main()
    124
    125

T:\__ML\TF_universal_Style_Transfer\stylize_video.py in main()
     87             style_rgb = style_img
     88
---> 89         stylized = wct_model.predict(content_img, style_rgb, args.alpha, args.swap5, args.ss_alpha)
     90
     91         if args.passes > 1:

T:\__ML\TF_universal_Style_Transfer\wct.py in predict(self, content, style, alpha, swap5, ss_alpha, adain)
     95         # Make sure shape is correct and pixels are in [0,1]
     96         content = self.preprocess(content)
---> 97         style   = self.preprocess(style)
     98
     99         s = time.time()

T:\__ML\TF_universal_Style_Transfer\wct.py in preprocess(image)
     63     def preprocess(image):
     64
---> 65         if len(image.shape) == 3:  # Add batch dimension
     66             image = np.expand_dims(image, 0)
     67         return image / 255.        # Range [0,1]

AttributeError: 'str' object has no attribute 'shape'`

**Comment by eridgd** [comment]
Seems like the content images from the vid are loaded and preprocessed properly, but the style image is not for whatever reason. Check that before this line
https://github.com/eridgd/WCT-TF/blob/38fedaa49e1da6885896748c827d227887045017/stylize_video.py#L79
that `style_img` is a proper image array.

**Comment by kobykotiv** [comment]
No. `style_img` is not a proper image array.

**Comment by eridgd** [comment]
I'm guessing it's a scipy-related issue, you can replace it with PIL for loading images here https://github.com/eridgd/WCT-TF/blob/38fedaa49e1da6885896748c827d227887045017/utils.py#L23-L27

**Comment by kobykotiv** [comment]
I solved the problem. I was trying to pass a `style_img` as a directory to use multiple styles to stylize short videos in bulk, just like you can stylize multiple images in the `stylize.py` script. Do you think you can implement batch video processing? I don't think it would be that hard to do... especially for short videos.

**Comment by eridgd** [comment]
I don't have the bandwidth to implement batch video processing at the moment, but it should be easy to port over from stylize.py. If you want to submit a PR that implements this I'll accept it.
