### ISSUE TITLE
Parameter settings for results in`gilbert_stylize.jpg`

### ISSUE THREAD

**Issue by vinsis** [eridgd/WCT-TF#25]
Hi, can you please elaborate on how did you get the results shown in the image `gilbert_stylize.jpg` under `samples` folder? What was the `alpha` used? How many reruns? Did you use all five layers or just one? Thanks.

**Comment by eridgd** [comment]
Hi,

From what I remember the main settings were:

* Alpha=0.8
* One pass
* All five encoder/decoders were used, started from layer 5

**Comment by vinsis** [comment]
Thank you
