### ISSUE TITLE
Arbitrary Style Transfer with Style-Attentional Networks

### ISSUE THREAD

**Issue by GlebSBrykin** [eridgd/WCT-TF#26]
How about implementing this algorithm: https://arxiv.org/abs/1812.02342v3? It works faster, but the quality is much higher than what is represented in the WCT.

**Comment by GlebSBrykin** [comment]
I have an exclusive example obtained directly from the developers. It can be used for quality evaluation.
Result from SANet:
![gogh_transfer](https://user-images.githubusercontent.com/36363358/52910585-a4124280-32aa-11e9-86b5-2a91e3547d3b.png)
Original:
![content](https://user-images.githubusercontent.com/36363358/52910590-b0969b00-32aa-11e9-9e49-29305eb5e25b.jpg)
Result from WCT:
![starrynight_result](https://user-images.githubusercontent.com/36363358/52910596-ca37e280-32aa-11e9-8171-be49e15dc180.png)

**Comment by o0t1ng0o** [comment]
Hi @GlebBrykin, how did you get the source code of SANet? Or did you implement it yourself?

**Comment by GlebSBrykin** [comment]
My implementations here: https://github.com/ColorfulSoft/StyleTransfer-Colorization-SuperResolution/tree/master/Style%20Transfer/2018.%20Arbitrary%20Style%20Transfer%20with%20Style-Attentional%20Networks and here: https://github.com/GlebBrykin/SANET. It will be finalized in the near future, but there is another implementation: https://github.com/mumair5393/Style-Transfer-with-Style-Attentional-Networks it looks more complete.
