### ISSUE TITLE
OpenCV error?

### ISSUE THREAD

**Issue by Sugarbank** [eridgd/WCT-TF#3]
Hi,
getting this error even though i'm only doing image stylisation....Do I still need OpenCV installed to run on images? Thanks in advance

paperspace@psg2ycs0:~/Desktop/NEURAL/WCT-TF-master$ python stylize.py --checkpoints models/relu5_1 models/relu4_1 models/relu3_1 models/relu2_1 models/relu1_1 --relu-targets relu5_1 relu4_1 relu3_1 relu2_1 relu1_1 --style-size 512 --alpha 1.0 --style-path /style --content-path /content --out-path /out
Traceback (most recent call last):
  File "stylize.py", line 7, in <module>
    from utils import preserve_colors_np
  File "/home/paperspace/Desktop/NEURAL/WCT-TF-master/utils.py", line 5, in <module>
    import cv2
ImportError: No module named cv2

**Comment by eridgd** [comment]
Hi,

Thanks for pointing that out! I've updated utils.py so that it doesn't require cv2 - https://github.com/eridgd/WCT-TF/commit/3cc418bba186bf16730c359bf5d0e9fe5a6862fd
