### ISSUE TITLE
Photorealistic Style Transfer

### ISSUE THREAD

**Issue by lQingRu** [eridgd/WCT-TF#30]
Hi, can this same model be used for photorealistic style transfer?

**Comment by eridgd** [comment]
It will likely give suboptimal results with artifacts/distortions that might be desirable for artistic transfer but not photorealism. I'd suggest looking at this paper from some of the same authors that extends the whiten-color feature transform specifically for photorealistic applications:

https://arxiv.org/abs/1802.06474
https://github.com/NVIDIA/FastPhotoStyle
